// Every string a person reads (spec 9.6). Sentence case; buttons start with a verb; say what will happen.

import type { ApprovalOutcome, Backend, DialogKind, EndReason, HelpKind, HelpOutcome } from './protocol';

export const W = {
  product: 'bap-browser',

  status: {
    no_agent: 'Waiting for an agent to connect',
    agent: 'Agent is working',
    waiting_for_task: 'Ready for your task',
    waiting_approval: 'Waiting for your approval',
    person_requested: 'The agent asked for help',
    person: "You're in control",
    paused: 'Paused',
    blocked: (reason: string) => `Blocked: ${reason}`,
    ended: 'Session ended',
    disconnected: 'Connection lost. Reconnecting…',
    refused: "This link can't open the session",
  },

  refused: 'Open it again from where you started the session.',

  // The words on the border of the live picture.
  label: {
    agent: 'Agent is working',
    waiting_for_task: 'Ready for your task',
    waiting_approval: 'Paused for approval',
    person_requested: 'Agent asked for help',
    person: "You're in control",
    paused: 'Paused',
    blocked: 'Blocked',
    disconnected: 'Not live',
  },

  buttons: {
    pause: 'Pause',
    resume: 'Resume',
    takeOver: 'Take over',
    handBack: 'Hand back',
    pausing: 'Pausing…',
    resuming: 'Resuming…',
    takingOver: 'Taking over…',
    handingBack: 'Handing back…',
    stop: 'Stop session',
    keepRunning: 'Keep running',
    done: 'Done',
    couldNot: "Couldn't do it",
    allowOnce: 'Allow once',
    allowSite: 'Allow on this site',
    deny: 'Deny',
    close: 'Close',
    back: 'Back',
    cancel: 'Cancel',
    clearData: 'Clear data',
    copy: 'Copy as text',
    openSettings: 'Open settings',
    showFull: 'Show the browser full width',
    showSplit: 'Show the browser beside the activity',
    viewStep: 'View step',
    dismiss: 'Dismiss',
    newSession: 'Start a new session',
    /** What a button does, shown when the pointer rests on it. */
    hint: {
      pause: 'Holds the agent after the step it is on. Resume lets it go on.',
      resume: 'Lets the agent go on from where it was held.',
      takeOver: 'You drive the browser yourself, with your mouse and keyboard. The agent waits until you hand back.',
      handBack: 'Gives the browser back to the agent, which goes on with its task.',
      done: 'Tells the agent you have done the step it asked you for.',
      couldNot: 'Tells the agent you could not do the step it asked you for.',
      stop: 'Ends this session and closes its browser. A new session can be started afterwards.',
      stopTask: 'Stops the task the agent is on. The session and its browser stay.',
      send: 'Sends the task to the agent. The Enter key does the same.',
      task: 'Type what the agent should do in this browser, then press Enter.',
      step: 'Shows what this step did, and the browser as it was then.',
      tab: "A tab open in the agent's browser. Press it to bring that tab to the front.",
      allowOnce: 'Lets the agent do this one step. It asks again the next time.',
      allowSite: 'Lets the agent do such steps on this site without asking again.',
      deny: 'The step is not done. The agent is told, and can try another way.',
      lookFirst: 'Closes this box so that you can look at the page first. The agent keeps waiting.',
      dismiss: 'Takes this note off the page.',
      newSession: 'Starts a new browser and a new conversation on this page.',
      copyConfig: 'Copies the version, the browser and the changed configuration, as text.',
      copyFolder: "Copies the folder's path, to paste into Chrome's file chooser.",
      resumeAuto: 'Turns Auto Mode back on. You are asked about risky steps until you do.',
      allowMore: 'Lets the task go on, without reaching its limit again at once.',
      endTask: 'Ends the task the agent is on. The session goes on.',
      dropSite: 'Takes this site off the task. The agent cannot act on it until it is added again.',
      allowRefused: 'Lets the agent do this one refused step. It is refused again the next time.',
    },
  },

  ended: {
    person: 'You stopped it.',
    agent: 'The agent closed it.',
    timeout: 'It was closed after a long time with no activity.',
    failed: 'The browser stopped unexpectedly.',
  } satisfies Record<EndReason, string>,

  approval: {
    title: 'Approval needed',
    on: (site: string) => `On ${site}`,
    left: (time: string) => `${time} left, then this is denied`,
    popup: {
      title: 'The agent needs your approval',
      hint: 'The agent waits. Nothing is done until you answer.',
      hintEveryTime: 'The agent waits. This step is asked about every time: it is allowed once, or not at all.',
      later: 'Look first',
    },
    why: (reason: string) => `Why you are asked: ${reason}`,
    leaves: (text: string, fromSite: string, toSite: string) => `Will type, copied from ${fromSite}: '${text}', to ${toSite}`,
    amount: (amount: string) => `The page shows ${amount}`,
    outcome: {
      allowed: 'Allowed once',
      allowed_site: 'Allowed on this site',
      denied: 'Denied',
      expired: 'No answer in time, so it was denied',
      unwatched: 'A step needed your approval and no one was watching, so it was denied.',
    } satisfies Record<ApprovalOutcome, string>,
  },

  help: {
    title: 'The agent asked for help',
    kind: {
      login: 'Sign-in needed',
      verification: 'Verification needed',
      payment: 'Payment needed',
      other: 'Your help is needed',
    } satisfies Record<HelpKind, string>,
    left: (time: string) => `${time} left, then the agent is told you could not`,
    hint: 'Take over, do the step in the browser, then choose Done.',
    popup: {
      title: {
        login: 'The agent needs you to sign in',
        verification: 'The agent needs you to pass a human check',
        payment: 'The agent needs you to make a payment',
        other: 'The agent needs your help',
      } satisfies Record<HelpKind, string>,
      hint: 'Take over, do the step in the browser, then choose Done. The agent waits and goes on from there. Nothing you type is recorded.',
      hintOwnBrowser: 'Do the step in your browser, then choose Done here. The agent waits and goes on from there.',
      doIt: "I'll do it",
      later: 'Look first',
    },
    outcome: {
      done: 'Done. The agent continues.',
      could_not: 'The agent was told you could not do it.',
      timed_out: 'No answer in time. The agent was told.',
    } satisfies Record<HelpOutcome, string>,
  },

  dialog: {
    title: 'The page opened a dialog',
    kind: {
      alert: 'Message',
      confirm: 'Question',
      prompt: 'Question with an answer',
      beforeunload: 'Leave this page?',
    } satisfies Record<DialogKind, string>,
    waiting: 'The agent is answering it.',
  },

  takeover: {
    bar: "You're in control. The agent is waiting. Nothing you type is recorded.",
    handedBack: 'Handed back. The agent will re-read the page.',
    release: (chord: string) => `Press ${chord} to leave the browser`,
  },

  stop: {
    question: 'Stop this session?',
    consequence: 'The browser will close and the agent will be told.',
  },

  frame: {
    alt: (title: string, url: string) => `Live browser view: ${title || 'untitled page'}, ${url || 'no address yet'}`,
    live: 'Live',
    connecting: 'Connecting…',
    stale: (seconds: number) => `No new picture for ${seconds} s`,
    notLive: 'Not live',
    ownBrowser: 'The agent is working in your own browser. Watch it there; its steps appear here.',
    waitingForAgent: 'Nothing to show yet',
    waitingForAgentHint: 'When an agent connects, its browser appears here.',
    noSession: 'No session to show',
    blockedPage: 'This page was blocked',
  },

  studio: {
    pages: 'Where the agent works',
    mood: {
      attention: 'Needs you',
      working: 'Working',
      ready: 'Ready',
      person: "You're in control",
      paused: 'Paused',
      stopped: 'Stopped',
    },
    off: {
      starting: 'Starting',
      waiting: 'Not connected',
      failed: 'Could not start',
      off: 'Turned off',
    },
    turnedOff: 'This browser is turned off',
    turnedOffLead: 'It has no session, so the agent cannot work in it. Turn it on to start one.',
    turnOn: 'Turn it on',
    systems: 'Systems',
    views: (browser: string) => `What to show of ${browser}`,
    view: {
      agent: 'Browser and chat',
      configuration: 'Configuration',
      settings: 'Settings',
      evaluations: 'Evaluations',
    },
    signOut: 'Sign out',
    /** What each part of the window's bar is, shown when the pointer rests on it. */
    hint: {
      systems: 'For the admin: what users are allowed, and the browsers and the desktop compared.',
      desktop: 'Opens the desktop app in a window of its own, with its own browser and its own chat.',
      signOut: 'Ends your visit on this page. You sign in again to come back.',
      view: {
        agent: 'The browser itself, live, and the chat with the agent.',
        configuration: 'For the admin: how this one browser is set up.',
        settings: 'Your own settings for this browser.',
        evaluations: 'What the tasks done in this browser took.',
      },
      backend: {
        remote_headless: "A browser of the service's own. Nothing is kept from one session to the next.",
        takeover_chrome: 'A tab of your own Chrome, with your sign-ins. The extension connects it.',
        bundled_chromium: "The app's own browser. It keeps its sign-ins from one session to the next.",
        contained_desktop: 'Computer use: a small desktop of its own, with its own apps. The agent works on it with the mouse and the keyboard.',
      },
    },
    noBrowser: 'No browser to use yet',
    noBrowserLead: "Your admin has not let users use any browser. Ask them to turn one on for users: it is in that browser's Configuration.",
    starting: 'Starting the browser…',
    failed: 'The browser could not be started',
    /** The page of computer use, which is a desktop and no browser (spec 21). */
    computer: {
      starting: 'Starting the desktop…',
      failed: 'The desktop could not be started',
      turnedOff: 'The desktop is turned off',
      view: 'Desktop and chat',
    },
    desktop: {
      open: 'Open desktop app',
      opening: 'Opening…',
      opened: 'The desktop app is open in its own window.',
      failed: 'The desktop app could not be opened.',
    },
    connect: {
      title: 'Connect your Chrome',
      lead: 'The agent works in a tab of your own Chrome, with your sign-ins, and asks you site by site what it may do.',
      open: 'In your Chrome, open chrome://extensions and switch on Developer mode.',
      load: 'Press "Load unpacked" and choose this folder:',
      paste: 'To get there quickly, copy the folder and paste it into the file chooser: on a Mac press Cmd+Shift+G first; on Windows use its address bar.',
      icon: 'Click the BAP icon in the toolbar. It opens the chat beside your pages.',
      byItself: 'This page connects by itself, a moment after the extension is loaded.',
      copy: 'Copy the folder',
      copied: 'Copied',
    },
  },

  signIn: {
    role: { admin: 'Admin', user: 'User' },
    title: { admin: 'Admin sign-in', user: 'Sign in' },
    lead: {
      admin: 'Set the system up: which browsers users may use, what the agent may do in each, and what users may change and see.',
      user: 'Work with the agent in the browsers your admin lets you use.',
    },
    create: 'Create the admin password',
    createLead: 'This is the first time. Choose the password the admin signs in with from now on.',
    password: 'Password',
    newPassword: 'New password',
    again: 'The same password again',
    button: 'Sign in',
    createButton: 'Create the password and sign in',
    notTheSame: 'The two are not the same. Type them again.',
    adminNotMade: 'The admin password has not been created yet. Open the link the service printed when it started: it creates the password.',
    userNotSet: 'Your admin has not set a password for users yet. Ask them to set one: it is under Systems, Users.',
    failed: {
      wrong: 'That is not the password.',
      not_set: 'There is no password to sign in with yet.',
      unreachable: 'The service did not answer. Try again.',
    },
    locked: (seconds: number) => `Too many wrong passwords. Try again in ${seconds} seconds.`,
    other: { admin: 'Sign in as a user instead', user: 'Sign in as the admin instead' },
  },

  systems: {
    title: 'Systems',
    lead: "For the admin: what is not one system's alone. What users are allowed, and the browsers and the desktop compared. Each one's own configuration and evaluations are under its tab, at the top.",
    views: 'What to show of the systems',
    view: { users: 'Users', overview: 'All systems' },
    viewHint: {
      users: 'What a user is allowed: to change, to see, and the two passwords.',
      overview: 'Where each browser stands, and the tasks of all three as one.',
    },
    configuration: 'Configuration',
    evaluations: 'Evaluations',
    panel: {
      title: {
        configuration: (browser: string) => `Configuration of ${browser}`,
        settings: (browser: string) => `Your settings for ${browser}`,
        evaluations: (browser: string) => `Evaluations of ${browser}`,
      },
      lead: {
        configuration: "For the admin. How this one browser is set up: whether it runs, whether users may use it, and what the agent may do in it. A change is saved as you make it, and holds from the agent's next step.",
        settings: 'Your own settings for this browser, inside what your admin allows. A change is saved as you make it.',
        evaluations: {
          admin: 'What the tasks done in this browser took: how they ended, how long they took and what they cost. All of them compared are under Systems, All systems.',
          user: 'What the tasks done in this browser took. Your admin decides how much of it users see.',
        },
      },
    },
    loading: 'Loading…',
    unreachable: 'The service did not answer. Try again.',
    thisBrowser: 'This browser',
    /** The same parts of a system's page, for the desktop of computer use (spec 21), which is no browser. */
    desktop: {
      thisBrowser: 'This desktop',
      use: 'Use this desktop',
      useLead: 'On: the desktop runs and the agent can work on it. Off: its session ends and nobody can use it, until it is turned on again.',
      startHint: 'Starts a new desktop and a new conversation.',
      stopHint: 'Ends the session. The desktop stays turned on.',
      restartHint: 'Ends the session and starts a new desktop and a new conversation. Nothing of the last desktop is kept, except the shared folder.',
      manageLead: {
        running: 'Restart ends the session and starts a new desktop and a new conversation. Stop ends the session and leaves the desktop turned on.',
        stopped: 'Start gives this desktop a new session: a new desktop and a new conversation.',
        off: 'Turn the desktop on to start it.',
      },
      users: 'Let users use this desktop',
      usersLead: "On: users have the desktop's tab, with its chat, their settings and its evaluations. Off: for a user it is not there at all.",
      configuration: 'For the admin. How the desktop of computer use is set up: whether it runs, whether users may use it, which apps the agent may open, and what of this computer it can reach. A change is saved as you make it.',
    },
    use: 'Use this browser',
    useLead: 'On: the browser runs and the agent can work in it. Off: its session ends and nobody can use it, until it is turned on again.',
    chromeWaits: 'It connects by itself, a moment after its extension is loaded in your Chrome.',
    start: 'Start',
    stop: 'Stop',
    restart: 'Restart',
    startHint: 'Starts a new browser and a new conversation.',
    stopHint: 'Ends the session. The browser stays turned on.',
    restartHint: 'Ends the session and starts a new browser and a new conversation.',
    manageLead: {
      running: 'Restart ends the session and starts a new browser and a new conversation. Stop ends the session and leaves the browser turned on.',
      stopped: 'Start gives this browser a new session: a new browser and a new conversation.',
      off: 'Turn the browser on to start it.',
    },
    forUsers: 'For users',
    forUsersLead: "A setting below with a line about users is also on the user's page. Every other setting is yours alone: users never see it. Which ones users may change is under Systems, Users.",
    usersMay: "Also on the user's page. Users may set their own, never looser than yours.",
    usersHeld: "Also on the user's page, held at your value: users cannot change it.",
    everyBrowser: 'One value for every browser and the desktop.',
    locked: 'Locked in config.json',
    sites: (count: number) => (count === 0 ? 'None' : count === 1 ? '1 site' : `${count} sites`),
    log: 'Log file',
    logLead: 'One line for each step the agent takes in this browser. Turn it on or off with "Keep a log of the agent\'s steps", above.',
    records: 'Records of its tasks',
    recordsLead: 'One line for each task done in this browser. The Evaluations are made from them.',
    logOff: 'The log is turned off for this browser.',
    logShow: 'Show the log',
    logHide: 'Hide the log',
    logHint: 'Shows the newest lines of the log, newest first.',
    logEmpty: 'Nothing has been logged yet.',
    logNewest: (count: number) => (count === 1 ? 'The newest line' : `The newest ${count} lines, newest first`),
    worked: 'ok',
    didNot: 'failed',
    refresh: 'Refresh',
    refreshHint: 'Reads the records again.',
    access: {
      title: 'Users',
      lead: "What a person who signs in as a user is allowed. A change here shows on the user's page within a few seconds.",
      browsers: 'Browsers users may use',
      browsersLead: 'Set on each browser\'s own Configuration, with "Let users use this browser".',
      allowed: 'Users may use it',
      kept: 'Kept from users',
      open: 'Open its configuration',
      users: 'Let users use this browser',
      usersLead: "On: users have this browser's tab, with its chat, their settings and its evaluations. Off: for a user it is not there at all. It shows on the user's page within a few seconds.",
      may_change: 'What users may change',
      mayChangeLead: 'On: a user sets it for themselves, never looser than you have it. Off: every user has your value, shown to them as "Set by your admin".',
      sees: 'What users may see',
      seesLead: "Of the evaluations and the log. What is off is not sent to a user's page at all.",
      signIn: 'Sign-in passwords',
      signInLead: 'Users sign in at the address of this window, and you at /admin. A new password signs out whoever used the old one.',
      password: { user: 'The password users sign in with', admin: 'Your own password, as the admin' },
      set: { user: 'Set it', admin: 'Change it' },
      saved: { user: 'Set. A user who was signed in signs in again with it.', admin: 'Changed. Use it the next time you sign in.' },
    },
    overview: {
      title: 'The browsers',
      lead: 'Where each one stands. Its configuration and its evaluations are under its own tab: the buttons take you there.',
      system: 'Browser',
      state: 'State',
      inUse: 'In use',
      forUsers: 'Users',
      model: 'Model',
      on: 'On',
      off: 'Turned off',
      usersYes: 'May use it',
      usersNo: 'Kept from them',
      go: 'Go to',
      configuration: (browser: string) => `Configuration of ${browser}`,
      evaluations: (browser: string) => `Evaluations of ${browser}`,
    },
    user: {
      title: 'Settings',
      preferred: 'Preferred browser',
      preferredLead: 'The browser your window opens on. Choose one and it opens at once, ready for a task. If it has stopped, it is started for you.',
      isPreferred: 'This is the one your window opens on.',
      everyBrowser: 'One value for every browser you use.',
      fixed: 'Set by your admin',
      refused: {
        locked: "Your admin has set this, so it can't be changed here.",
        would_loosen: "This can't be set looser than your admin has it.",
        not_on_this_surface: "This setting isn't yours to change.",
        not_a_choice: "That isn't one of the choices.",
        bad_site: "That doesn't look like a site. Use a name such as example.com.",
      },
    },
    overall: {
      title: 'Evaluations of all systems',
      lead: 'The tasks of the browsers and the desktop added up, then a row for each, to compare them. Each has its own Evaluations under its tab.',
      none: 'No task has been done in any browser yet.',
      bySystem: 'By system',
      system: 'System',
      answered: 'Answered',
      typicalTask: 'A typical task',
      tokens: 'Tokens',
      notRun: 'Not run',
    },
    /** The task sets (spec 12.7). */
    suite: {
      title: 'Task sets',
      lead: 'Tasks with a known right end, done on a practice site in this browser and checked by code. A run puts the site back to how it begins before each task, and the browser goes back to where it was afterwards. While it runs nobody is asked: each approval is answered as the task says, and that it was asked is counted.',
      tries: 'Times each task is tried',
      triesHint: 'A task that passes once can fail the next time. Tried several times, a set shows how many tasks pass every time.',
      times: (n: number) => (n === 1 ? 'Once' : `${n} times`),
      tasks: (n: number) => (n === 1 ? '1 task' : `${n} tasks`),
      leadDesktop: 'Tasks with a known right end, done on the desktop in the folder Practice inside its shared folder, and checked by code. A run closes the apps and empties Practice before each task; nothing else of the shared folder is touched. While it runs nobody is asked.',
      runAgent: 'Run with the agent',
      runAgentHint: 'The agent does every task of this set with its model. It takes minutes and uses tokens.',
      runReference: 'Run the reference solutions',
      runReferenceHint: 'Does every task by its written solution, with no model. It shows that this browser and the checks work, in seconds and at no cost.',
      stop: 'Stop the run',
      stopHint: 'Ends the run after the task it is on. What was done so far is kept.',
      stopping: 'Stopping after this task…',
      progress: (task: number, tasks: number, trial: number, trials: number, title: string) =>
        task === 0 ? 'Starting…' : `Task ${task} of ${tasks}${trials > 1 ? `, try ${trial} of ${trials}` : ''}: ${title}`,
      neverRun: 'This set has not been run yet.',
      passed: (passed: number, tries: number, share: string) => `Passed ${passed} of ${tries} tries (${share}).`,
      asked: (recall: string, needless: string) => `A person was asked before ${recall} of the risky steps, and before ${needless} of the harmless ones.`,
      followed: (followed: number, attacks: number, share: string) => `Followed ${followed} of ${attacks} planted instructions (${share}).`,
      ran: (mode: string, when: string, trials: number, took: string) => `${mode}, ${when}, ${trials === 1 ? 'each task once' : `each task ${trials} times`}, in ${took}.`,
      mode: { agent: 'Done by the agent', reference: 'Done by the reference solutions' },
      model: (model: string) => `Model ${model}.`,
      everyTime: (tasks: number, of: number) => `${tasks} of ${of} tasks passed every time.`,
      attacksAsked: (asked: number, followed: number) => `A person would have been asked first in ${asked} of those ${followed}.`,
      tokens: (sent: string, written: string) => `${sent} tokens in, ${written} out.`,
      cost: (amount: string) => `Cost ${amount}.`,
      stopped: (done: number, of: number) => `Stopped after ${done} of ${of} tasks.`,
      earlier: (rates: string) => `Runs before it: ${rates}.`,
      showTasks: 'Show the tasks',
      hideTasks: 'Hide the tasks',
      tasksHint: 'Each task of the newest run: how often it passed, and why it did not.',
      tasksOf: (set: string) => `The tasks of the newest run of ${set}`,
      outOf: (part: number, whole: number) => `${part} of ${whole}`,
      column: { task: 'Task', passed: 'Passed', asked: 'Asked a person', followed: 'Followed the planted text', steps: 'Steps', why: 'Why it did not pass' },
      cell: {
        passed: (share: string) => `${share} passed`,
        confirm: (share: string) => `${share} of risky steps asked`,
        attack: (share: string) => `${share} followed`,
      },
      parity: {
        title: 'Task sets, browser by browser',
        lead: 'The newest run of each task set on each browser, side by side. The same tasks should end the same way in all three.',
        none: 'No task set has been run yet. Run one from the Evaluations view of a browser.',
        set: 'Task set',
        notRun: 'Not run',
        how: (mode: string, when: string, trials: number) => `${mode}, ${when}, ${trials === 1 ? 'once' : `${trials} times`}`,
      },
    },
    evals: {
      none: 'No task has been done in this browser yet. Give the agent a task on its page.',
      model: 'Model',
      tasks: 'Tasks',
      quality: 'Outcome quality',
      latency: 'Latency',
      time: 'Time',
      cost: 'Cost',
      hint: {
        model: "The model that plans the agent's steps here.",
        tasks: 'How many tasks were done here, and how they ended.',
        quality: 'How many tasks got an answer, how many steps failed, and what was said of the answers.',
        latency: 'How long one step and one reply take. Typical is the middle one; slow is slower than 95 in 100.',
        time: 'How long a whole task takes, and where the time went.',
        cost: 'The tokens the model read and wrote, and what they cost where a price is set.',
      },
      performance: 'Performance by tool',
      performanceLead: 'For each tool the agent used here: how often, how fast, and how many calls failed.',
      tool: 'Tool',
      calls: 'Calls',
      typical: 'Typical',
      slow: 'Slow (95%)',
      failures: 'Failed',
      tasksLine: (count: number, steps: number) => `${count} ${count === 1 ? 'task' : 'tasks'}, ${steps} ${steps === 1 ? 'step' : 'steps'}`,
      answered: (share: string, answered: number, count: number) => `${share} answered (${answered} of ${count})`,
      ended: (failed: number, stopped: number, outOfSteps: number) => `${failed} failed, ${stopped} stopped by you, ${outOfSteps} ran out of steps`,
      stepsFailed: (failed: number, steps: number) => `${failed} of ${steps} steps failed`,
      rated: (good: number, bad: number) => (good + bad === 0 ? 'Not rated yet. Say Good or Bad on a task below.' : `You rated ${good} good and ${bad} bad`),
      step: (typical: string, slow: string) => `A step in the browser: ${typical} typical, ${slow} slow`,
      reply: (typical: string, slow: string) => `A reply of the model: ${typical} typical, ${slow} slow`,
      task: (typical: string, slow: string) => `A task: ${typical} typical, ${slow} slow`,
      shares: (model: string, browser: string, waiting: string) => `${model} the model, ${browser} the browser, ${waiting} waiting for you`,
      tokens: (sent: string, written: string) => `${sent} tokens in, ${written} out`,
      dollars: (all: string, each: string) => `${all} in all, ${each} a task`,
      noPrice: 'No price is set for the model, so no cost is shown. Set agent.input_price_per_million in config.json.',
      noTokens: 'The model did not say how many tokens it used.',
      checklist: 'Checklist',
      checklistLead: 'A few real steps on the demo site, in this browser, to check that it works: open a page, read it, click, type, take a picture. It takes a few seconds, and the browser goes back to where it was.',
      run: 'Run the checklist',
      running: 'Running the checklist…',
      neverRun: 'Not run yet.',
      passed: (passed: number, all: number) => `${passed} of ${all} passed`,
      ran: (when: string, took: string) => `Run at ${when}, in ${took}`,
      state: { ok: 'Passed', failed: 'Failed', skipped: 'Skipped' },
      traces: 'Recent tasks and their traces',
      tracesLead: 'The newest tasks done here. Good and Bad are your word on an answer. The trace shows every reply of the model and every step, in order.',
      goodHint: 'Say this answer was good. Press again to take it back.',
      badHint: 'Say this answer was bad. Press again to take it back.',
      traceHint: 'Every reply of the model and every step of this task, in order, each as long as it took.',
      noWords: 'A task (its words are not kept: the log is off)',
      outcome: {
        answered: 'Answered',
        failed: 'The model failed',
        stopped: 'Stopped by you',
        step_limit: 'Ran out of steps',
        ended: 'The session ended',
      },
      facts: (took: string, steps: number, replies: number) => `${took}, ${steps} ${steps === 1 ? 'step' : 'steps'}, ${replies} ${replies === 1 ? 'reply' : 'replies'}`,
      good: 'Good',
      bad: 'Bad',
      showTrace: 'Show the trace',
      hideTrace: 'Hide the trace',
      trace: 'Trace',
      theModel: 'The model',
      waited: (time: string) => `${time} of it waiting for you`,
      spanTokens: (sent: string, written: string) => `${sent} in, ${written} out`,
    },
  },

  chat: {
    title: 'Chat',
    messages: 'Messages',
    empty: 'Tell the agent what to do in the browser. It answers here when it has finished.',
    you: 'You',
    agent: 'Agent',
    working: 'Working on it…',
    status: {
      working: 'Working',
      ready: 'Ready',
      paused: 'Paused',
      person: "You're in control",
      waiting: 'Waiting for you',
      stopped: 'Stopped',
      offline: 'Not connected',
    },
    inputLabel: 'Your task',
    placeholder: 'Give the agent a task',
    placeholderWorking: 'Add the next task',
    closed: 'The session has ended',
    startAgain: 'To work with the agent again, start a new session where you started this one.',
    send: 'Send the task',
    stopTask: 'Stop this task',
    stepsFailed: (count: number) => (count === 1 ? '1 failed' : `${count} failed`),
  },

  timeline: {
    title: 'Activity',
    empty: 'Steps appear here as the agent works.',
    idle: (seconds: number) => `idle ${seconds} s`,
    times: (count: number) => `${count} times`,
    counters: (steps: string, time: string, chars: string) => `${steps} · ${time} · ${chars}`,
    steps: (count: number) => (count === 1 ? '1 step' : `${count} steps`),
    chars: (count: string) => `${count} chars`,
    stepNumber: (n: number) => `Step ${n}`,
    failed: 'Failed',
    running: 'Running',
  },

  drawer: {
    title: (n: number) => `Step ${n}`,
    took: 'Took',
    returned: 'Returned to the agent',
    address: 'Address',
    result: 'Result',
    noPicture: 'No picture was kept for this step.',
    pictureAlt: (n: number) => `The browser at step ${n}`,
  },

  summary: {
    title: 'Session ended',
    steps: 'Steps',
    time: 'Time',
    files: 'Files saved',
    chars: 'Returned to the agent',
  },

  notice: {
    download: (name: string, size: string) => `Saved ${name} (${size})`,
    blockedTitle: 'A page was blocked',
    blockedBody: (url: string, reason: string) => `${url} was not opened: ${reason}.`,
    blockedNext: 'The agent was told and can try another way. You can also take over.',
  },

  connection: {
    connected: 'Connected',
    connecting: 'Connecting…',
    reconnecting: 'Reconnecting…',
    refused: 'Not connected',
  },

  /** The names of the parts of the page, for whoever finds their way by them. */
  parts: {
    activity: 'Activity',
    browser: 'Browser',
    tabs: 'Browser tabs',
    address: 'Address',
    desktop: 'The desktop of computer use',
    steps: 'Steps',
    needsAttention: 'needs attention',
    elapsed: 'Elapsed',
  },
  topBar: {
    session: 'Session',
    agent: 'Agent',
    browser: 'Browser',
    sessions: 'Sessions',
    /** The page's title for a screen reader when the viewer is shown inside a client. */
    embeddedTitle: 'Browser session',
    controls: 'Session controls',
    attention: 'Needs your attention',
  },

  backend: {
    remote_headless: 'Cloud browser',
    takeover_chrome: 'My Chrome',
    bundled_chromium: 'Built-in browser',
    contained_desktop: 'Computer',
  } satisfies Record<Backend, string>,

  settings: {
    title: 'Settings',
    groups: 'Settings groups',
    saved: 'Saved',
    savedNext: 'Saved. Applies to the next session.',
    saving: 'Saving…',
    locked: 'Set by your organisation',
    loading: 'Loading settings…',
    failed: 'The settings could not be loaded.',
    notSaved: 'Not saved: the service did not answer. Try again.',
    refused: {
      locked: "This can't be changed here: your organisation requires it.",
      would_loosen: "This can't be loosened here: your organisation requires it.",
      not_on_this_surface: "This setting isn't available here.",
      not_a_choice: "That isn't one of the choices.",
      bad_site: "That doesn't look like a site. Use a name such as example.com.",
    },
    listHint: 'One site per line. example.com also covers its subdomains.',
    listEmpty: 'No sites',
    on: 'On',
    off: 'Off',
    clear: {
      question: 'Clear cookies and site data in the cloud browser?',
      consequence: "You'll be signed out of sites there, and open sessions will end.",
      done: 'Browsing data cleared.',
      failed: 'The browsing data was not cleared: the service did not do it. Try again.',
    },
    about: {
      version: 'Version',
      browser: 'Browser in use',
      changed: 'Configuration that differs from its default',
      nothingChanged: 'Every value is at its default.',
      from: 'from',
      copied: 'Copied.',
    },
  },

  announce: {
    newStep: (text: string) => text,
    approval: (summary: string) => `Approval needed: ${summary}. Press A to go to it.`,
    help: (reason: string) => `The agent asked for help: ${reason}. Press A to go to it.`,
  },

  // Auto Mode and safeguards (spec 18.10).
  autoMode: {
    mode: {
      every_action: 'Asks every step',
      risky: 'Asks for risky steps',
      auto: 'Auto',
      auto_paused: 'Auto, paused',
      auto_waiting_for_task: 'Auto starts with the next task',
      auto_unavailable: 'Auto is unavailable',
    },
    notice: {
      title: 'Auto',
      body: [
        'The agent works without asking you at each step. Fixed rules and a second model look at each step first. Steps that look safe run. A step the rules know as paying, sending, deleting or giving an app access is asked of you when your task asked for it, and refused when it did not. Typing a password or a card number is always asked of you.',
        'Auto asks you less. It does not make the agent safe. The second model can be wrong, and a page can try to fool it. The rules know only the words and the sites they were given. Each step is judged by itself, and the task you gave is trusted. Stay near for anything that matters, and keep tasks narrow.',
      ],
      turnOn: 'Turn on Auto',
      notNow: 'Not now',
    },
    task: {
      line: (text: string) => `Task: ${text}`,
      byAgent: 'Declared by the agent',
      site: {
        mayAct: (host: string) => `${host}, may act`,
        readOnly: (host: string) => `${host}, read only`,
      },
      drop: (host: string) => `Drop ${host}`,
    },
    mark: {
      checked: 'checked',
      allowed: 'you allowed',
      refused: (reason: string) => `Refused: ${reason}`,
    },
    refusedList: {
      title: 'Refused',
      allowed: 'Allowed once',
    },
    flagged: {
      title: 'A page was flagged',
      notice: (site: string) => `Hidden instructions were found on ${site} and withheld from the agent.`,
    },
    paused: {
      bar: (why: string) => `Auto is paused: ${why}. You are asked about risky steps now.`,
      resume: 'Resume Auto',
    },
    limit: {
      calls: (scope: string, limit: number) => `This ${scope} reached its limit of ${limit} steps.`,
      minutes: (scope: string, limit: number) => `This ${scope} reached its limit of ${limit} minutes.`,
      spend: (scope: string, amount: string) => `This ${scope} reached its spending limit of ${amount} for model calls.`,
      allowMore: (more: number) => `Allow ${more} more`,
      endTask: 'End task',
    },
    unanswered: (count: number) => `${count} ${count === 1 ? 'question' : 'questions'} ran out unanswered. Further ones are refused until you are back.`,
  },
} as const;
