"""The settings catalogue (spec 10.2): each setting a person can change, the configuration key it
changes, the surfaces it appears on, and how a person's value is limited by the deployment's.

The settings screen is drawn from this, so a setting is defined once. A build lists only the
settings whose feature it contains.
"""

from __future__ import annotations

from collections.abc import Mapping

from bap_browser.settings.kinds import (
    BROWSERS,
    CLOUD,
    COMPUTER,
    EVERYWHERE,
    NOT_ON_MOBILE,
    About,
    Action,
    ActivityLog,
    AgentModel,
    ApprovalWait,
    AskBefore,
    Choice,
    Enabled,
    Entry,
    Guard,
    Option,
    SiteList,
    StaySignedIn,
    StepLimit,
    Switch,
)

ENABLED = Enabled(
    id="system_enabled",
    group="Browser",
    surfaces=EVERYWHERE,
    title="Use this browser",
    description="Turns this browser on or off in the window. Turning it off ends its session.",
    per_system=True,
    only_per_system=True,
)

CATALOGUE: tuple[Entry, ...] = (
    ENABLED,
    StaySignedIn(
        id="stay_signed_in",
        group="Browser",
        surfaces=EVERYWHERE,
        title="Stay signed in to sites",
        description="Keeps the cloud browser's cookies and site data from one session to the next, so sites stay signed in.",
        key="browser.user_data_dir",
        applies="next_session",
        backends=(CLOUD,),
    ),
    AgentModel(
        id="agent_model",
        group="Agent",
        surfaces=EVERYWHERE,
        title="Model",
        description="The model that plans the agent's steps. A change holds from the next task.",
        key="agent.model",
        options=(),
        dropdown=True,
        per_system=True,
    ),
    AskBefore(
        id="ask_before",
        user=True,
        per_system=True,
        group="Approvals",
        surfaces=EVERYWHERE,
        title="Ask before",
        description="When the agent must stop and wait for a person's approval before it acts.",
        key="safety.ask_before",
        tighten=True,
        options=(
            Option("risky", "Risky actions", "Uploads, page scripts and whatever the admin lists"),
            Option("every_action", "Every action", "Each click, key press and page change"),
            Option(
                "auto",
                "Auto",
                "A check looks at each step. Safe steps run, and you are asked only about the risky ones",
            ),
        ),
    ),
    Switch(
        id="offer_auto",
        per_system=True,
        group="Approvals",
        surfaces=EVERYWHERE,
        title="Offer Auto",
        description='Let people choose Auto for "Ask before". It asks less: a check decides each step, and it can be wrong.',
        key="safety.auto_mode.offered",
    ),
    ApprovalWait(
        id="approval_wait",
        user=True,
        per_system=True,
        group="Approvals",
        surfaces=EVERYWHERE,
        title="Wait for my answer",
        description="How long the agent waits for an answer to an approval. With no answer by then, the action is denied.",
        key="control.approval_timeout_s",
        options=(),
        dropdown=True,
    ),
    Choice(
        id="remember_site_approval",
        user=True,
        per_system=True,
        group="Approvals",
        surfaces=EVERYWHERE,
        title='Remember "Allow on this site"',
        description='After "Allow on this site", how long the agent may go on acting on that site without asking again.',
        key="control.site_grant_lifetime",
        tighten=True,
        dropdown=True,
        options=(Option("session", "Until the session ends"), Option("none", "Never")),
    ),
    Choice(
        id="scan_pages",
        backends=BROWSERS,
        user=True,
        per_system=True,
        group="Safety",
        surfaces=EVERYWHERE,
        title="Check pages for hidden instructions",
        description="A web page can hold text that tries to give the agent orders. What is found is kept from the agent, and you are told.",
        key="safeguards.incoming.scan",
        tighten=True,
        options=(
            Option("off", "Off", "Pages are not checked"),
            Option("local", "On this computer", "Fixed rules only. Nothing leaves this computer"),
            Option(
                "local_then_model",
                "On this computer, then a model",
                "What the rules find suspicious is sent to the model for a second opinion",
            ),
        ),
    ),
    Guard(
        id="cross_site_text",
        backends=BROWSERS,
        user=True,
        per_system=True,
        group="Safety",
        surfaces=EVERYWHERE,
        title="Copying between sites",
        description="Ask me before the agent types or sends, on one site, text that it read on another.",
        key="safeguards.outgoing.cross_site_text",
        tighten=True,
    ),
    SiteList(
        id="sensitive_sites",
        backends=BROWSERS,
        user=True,
        per_system=True,
        group="Safety",
        surfaces=EVERYWHERE,
        title="Sensitive sites",
        description="Sites the agent may enter only with your yes, such as your bank. They are added to the ones already listed.",
        key="safeguards.sites.sensitive.more",
        adds_to_deployment=True,
    ),
    StepLimit(
        id="task_limit",
        user=True,
        per_system=True,
        group="Limits",
        surfaces=EVERYWHERE,
        title="Steps in one task",
        description="The most steps the agent may take for one task before it stops and waits for you.",
        key="limits.max_calls",
        tighten=True,
        options=(),
        dropdown=True,
    ),
    SiteList(
        id="blocked_sites",
        backends=BROWSERS,
        user=True,
        per_system=True,
        group="Sites",
        surfaces=EVERYWHERE,
        title="Blocked sites",
        description="Sites the agent must never open.",
        key="safety.blocked_domains",
        adds_to_deployment=True,
    ),
    SiteList(
        id="allowed_sites",
        backends=BROWSERS,
        user=True,
        per_system=True,
        group="Sites",
        surfaces=EVERYWHERE,
        title="Only allow these sites",
        description="When this list has entries, the agent may open only these sites. Empty: any site that is not blocked.",
        key="safety.allowed_domains",
        adds_to_deployment=False,
    ),
    Switch(
        id="allow_downloads",
        backends=BROWSERS,
        per_system=True,
        group="Files",
        surfaces=EVERYWHERE,
        title="Let the agent download files",
        description="On: the agent may download files, saved where you can find them after the session. Off: it cannot.",
        key="browser.downloads.enabled",
        tighten=True,
    ),
    Switch(
        id="allow_uploads",
        backends=BROWSERS,
        per_system=True,
        group="Files",
        surfaces=EVERYWHERE,
        title="Let the agent upload files",
        description="On: the agent may upload a file to a site; each upload still asks for approval. Off: it cannot.",
        key="browser.uploads.enabled",
        tighten=True,
    ),
    ActivityLog(
        id="activity_log",
        per_system=True,
        group="Privacy",
        surfaces=EVERYWHERE,
        title="Keep a log of the agent's steps",
        description="Writes one line for each step the agent takes. What is typed is never logged, only its length.",
        key="logging.event_log",
    ),
    Action(
        id="clear_browsing_data",
        backends=BROWSERS,
        group="Privacy",
        surfaces=EVERYWHERE,
        title="Clear browsing data",
        description="Deletes cookies and site data in the cloud browser.",
        button="Clear data",
        question="Clear cookies and site data in the cloud browser?",
        consequence="You'll be signed out of sites there, and open sessions will end.",
    ),
    Choice(
        id="picture_quality",
        user=True,
        per_system=True,
        group="Live view",
        surfaces=EVERYWHERE,
        title="Picture quality",
        description="How sharp the live picture of the browser is. A sharper picture uses more data.",
        key="viewer.quality",
        options=(
            Option("standard", "Standard"),
            Option("data_saver", "Data saver", "For a slow or metered connection"),
            Option("high", "High", "For a fast connection"),
        ),
    ),
    Switch(
        id="show_agent_pointer",
        user=True,
        group="Live view",
        surfaces=EVERYWHERE,
        title="Show where the agent is acting",
        description="Outlines the element and shows the agent's pointer over the live picture.",
        key="viewer.show_agent_pointer",
    ),
    Choice(
        id="colour_mode",
        user=True,
        group="Appearance",
        surfaces=EVERYWHERE,
        title="Colour mode",
        description="The colours of this window: light, dark, or the same as your device.",
        key="viewer.theme",
        options=(Option("system", "Match system"), Option("light", "Light"), Option("dark", "Dark")),
    ),
    Switch(
        id="page_scripts",
        backends=BROWSERS,
        per_system=True,
        group="Advanced",
        surfaces=NOT_ON_MOBILE,
        title="Let the agent run scripts in pages",
        description="Offers the agent a tool that runs JavaScript in the page. Each use still asks.",
        key="browser.javascript.allow_evaluate",
        tighten=True,
    ),
    Switch(
        id="code_tool",
        backends=BROWSERS,
        per_system=True,
        group="Advanced",
        surfaces=NOT_ON_MOBILE,
        title="Let the agent run scripts of several steps",
        description="Offers the agent a tool that does several steps in one call. Each step is still checked.",
        key="code.enabled",
        tighten=True,
    ),
    Choice(
        id="computer_runs",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Where the agent works",
        description="The contained desktop, or this Mac itself through the helper you start on it. On this Mac the agent works among your own files and apps; you stop it at once by pushing the pointer into the top left corner.",
        key="computer.runs",
        applies="next_session",
        options=(
            Option("container", "The contained desktop", "A small desktop of its own, in a container"),
            Option("mac", "This Mac", "Your own screen, mouse and keyboard, through bap-browser helper"),
        ),
    ),
    Switch(
        id="computer_mac_any_app",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="On this Mac, let the agent open any app",
        description="As GPT-6 Astra does: the agent may open any app on your Mac by its name. Each opening asks you first. Holds from the next start of the helper.",
        key="computer.mac_any_app",
        applies="next_session",
    ),
    Choice(
        id="computer_screen",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Screen size",
        description="The desktop's screen. A model points best on a screen of about this size; a larger one is shrunk for it.",
        key="computer.screen",
        applies="next_session",
        options=(
            Option("1024x768", "1024 by 768"),
            Option("1280x800", "1280 by 800"),
            Option("1366x768", "1366 by 768"),
        ),
    ),
    Switch(
        id="computer_zoom",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Let the agent zoom in",
        description="Offers the agent a tool that looks at a part of the screen at twice its size, to read small print.",
        key="computer.zoom",
    ),
    Switch(
        id="computer_picture_after_action",
        user=True,
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="A picture after each action",
        description="Each click, key or typing comes back with a picture of the screen. The agent takes fewer steps; each step costs more tokens.",
        key="computer.picture_after_action",
    ),
    Guard(
        id="computer_ask_before_apps",
        user=True,
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Ask me before an app opens",
        description="The agent waits for your yes before it opens any app on the desktop.",
        key="computer.ask_before_apps",
        tighten=True,
    ),
    Switch(
        id="computer_text_editor",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Text editor",
        description="Lets the agent open the text editor on the desktop. Turning it on holds from the next session; turning it off holds at once.",
        applies="next_session",
        key="computer.apps.text_editor",
    ),
    Switch(
        id="computer_files",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Files",
        description="Lets the agent open the file manager on the desktop. Turning it on holds from the next session; turning it off holds at once.",
        applies="next_session",
        key="computer.apps.files",
    ),
    Switch(
        id="computer_calculator",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Calculator",
        description="Lets the agent open the calculator on the desktop. Turning it on holds from the next session; turning it off holds at once.",
        applies="next_session",
        key="computer.apps.calculator",
    ),
    Switch(
        id="computer_terminal",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Terminal",
        description="Lets the agent open a terminal. A terminal runs any command inside the desktop. Turning it on holds from the next session; turning it off holds at once.",
        applies="next_session",
        key="computer.apps.terminal",
    ),
    Switch(
        id="computer_share_folder",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Share a folder with the desktop",
        description="Shows one folder of this computer on the desktop, as Files. What the agent saves there, you have. Nothing else of this computer is seen from the desktop.",
        key="computer.share_folder",
        applies="next_session",
    ),
    Switch(
        id="computer_network",
        backends=(COMPUTER,),
        per_system=True,
        group="Computer",
        surfaces=NOT_ON_MOBILE,
        title="Let the desktop reach the network",
        description="Off: the desktop has no network at all. On: apps on it can reach the internet.",
        key="computer.network",
        applies="next_session",
    ),
    About(
        id="about",
        group="Advanced",
        surfaces=NOT_ON_MOBILE,
        title="About this deployment",
        description="The version, the browser in use and the configuration that differs from the defaults.",
    ),
)

BY_ID: Mapping[str, Entry] = {entry.id: entry for entry in CATALOGUE}

# Each setting as the admin has it: every choice open (spec 4.11).
FREE: Mapping[str, Entry] = {entry.id: entry.free() for entry in CATALOGUE}
